[package]
name = "rust-guessing-game"
version = "0.1.0"
authors = ["Alex Black <wa7@sa34.cx>"]
description = "Command line Guessing Game"
license = "MIT"
repository = "https://github.com/wa7sa34cx/rust-guessing-game"
edition = "2018"
readme = "README.md"

[dependencies]
rand = "0.8.4"